name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup imagemagick
        uses: mfinelli/setup-imagemagick@v5
      - name: Setup pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 3.1.11.1
      - name: Generate HTML pages
        run: |
          ./_src/build.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "release: generate and publish"
          branch: ${{ github.head_ref }}
          file_pattern: "*.html favicon.ico"
